var searchData=
[
  ['ianimatedmesh',['IAnimatedMesh',['../classirr_1_1scene_1_1_i_animated_mesh.html',1,'irr::scene']]],
  ['ianimatedmeshmd2',['IAnimatedMeshMD2',['../classirr_1_1scene_1_1_i_animated_mesh_m_d2.html',1,'irr::scene']]],
  ['ianimatedmeshmd3',['IAnimatedMeshMD3',['../classirr_1_1scene_1_1_i_animated_mesh_m_d3.html',1,'irr::scene']]],
  ['ianimatedmeshscenenode',['IAnimatedMeshSceneNode',['../classirr_1_1scene_1_1_i_animated_mesh_scene_node.html',1,'irr::scene']]],
  ['ianimationendcallback',['IAnimationEndCallBack',['../classirr_1_1scene_1_1_i_animation_end_call_back.html',1,'irr::scene']]],
  ['iaplayer',['IAPlayer',['../class_i_a_player.html',1,'']]],
  ['iarchiveloader',['IArchiveLoader',['../classirr_1_1io_1_1_i_archive_loader.html',1,'irr::io']]],
  ['iattribute',['IAttribute',['../classirr_1_1io_1_1_i_attribute.html',1,'irr::io']]],
  ['iattributeexchangingobject',['IAttributeExchangingObject',['../classirr_1_1io_1_1_i_attribute_exchanging_object.html',1,'irr::io']]],
  ['iattributes',['IAttributes',['../classirr_1_1io_1_1_i_attributes.html',1,'irr::io']]],
  ['iaudiorecorder',['IAudioRecorder',['../classirrklang_1_1_i_audio_recorder.html',1,'irrklang']]],
  ['iaudiostream',['IAudioStream',['../classirrklang_1_1_i_audio_stream.html',1,'irrklang']]],
  ['iaudiostreamloader',['IAudioStreamLoader',['../classirrklang_1_1_i_audio_stream_loader.html',1,'irrklang']]],
  ['ibillboardscenenode',['IBillboardSceneNode',['../classirr_1_1scene_1_1_i_billboard_scene_node.html',1,'irr::scene']]],
  ['ibillboardtextscenenode',['IBillboardTextSceneNode',['../classirr_1_1scene_1_1_i_billboard_text_scene_node.html',1,'irr::scene']]],
  ['ibonescenenode',['IBoneSceneNode',['../classirr_1_1scene_1_1_i_bone_scene_node.html',1,'irr::scene']]],
  ['iburningshader',['IBurningShader',['../classirr_1_1video_1_1_i_burning_shader.html',1,'irr::video']]],
  ['ibytein',['IByteIn',['../struct_i_byte_in.html',1,'']]],
  ['ibyteout',['IByteOut',['../struct_i_byte_out.html',1,'']]],
  ['icamerascenenode',['ICameraSceneNode',['../classirr_1_1scene_1_1_i_camera_scene_node.html',1,'irr::scene']]],
  ['icapturedaudiodatareceiver',['ICapturedAudioDataReceiver',['../classirrklang_1_1_i_captured_audio_data_receiver.html',1,'irrklang']]],
  ['icolladameshwriter',['IColladaMeshWriter',['../classirr_1_1scene_1_1_i_collada_mesh_writer.html',1,'irr::scene']]],
  ['icolladameshwriternames',['IColladaMeshWriterNames',['../classirr_1_1scene_1_1_i_collada_mesh_writer_names.html',1,'irr::scene']]],
  ['icolladameshwriterproperties',['IColladaMeshWriterProperties',['../classirr_1_1scene_1_1_i_collada_mesh_writer_properties.html',1,'irr::scene']]],
  ['icolladaprefab',['IColladaPrefab',['../classirr_1_1scene_1_1_i_collada_prefab.html',1,'irr::scene']]],
  ['icollisioncallback',['ICollisionCallback',['../classirr_1_1scene_1_1_i_collision_callback.html',1,'irr::scene']]],
  ['icompressprogress',['ICompressProgress',['../struct_i_compress_progress.html',1,'']]],
  ['icursorcontrol',['ICursorControl',['../classirr_1_1gui_1_1_i_cursor_control.html',1,'irr::gui']]],
  ['idepthbuffer',['IDepthBuffer',['../classirr_1_1video_1_1_i_depth_buffer.html',1,'irr::video']]],
  ['idummytransformationscenenode',['IDummyTransformationSceneNode',['../classirr_1_1scene_1_1_i_dummy_transformation_scene_node.html',1,'irr::scene']]],
  ['idynamicmeshbuffer',['IDynamicMeshBuffer',['../classirr_1_1scene_1_1_i_dynamic_mesh_buffer.html',1,'irr::scene']]],
  ['ieventreceiver',['IEventReceiver',['../classirr_1_1_i_event_receiver.html',1,'irr']]],
  ['ifilearchive',['IFileArchive',['../classirr_1_1io_1_1_i_file_archive.html',1,'irr::io']]],
  ['ifilefactory',['IFileFactory',['../classirrklang_1_1_i_file_factory.html',1,'irrklang']]],
  ['ifilelist',['IFileList',['../classirr_1_1io_1_1_i_file_list.html',1,'irr::io']]],
  ['ifilereadcallback',['IFileReadCallBack',['../classirr_1_1io_1_1_i_file_read_call_back.html',1,'irr::io']]],
  ['ifilereader',['IFileReader',['../classirrklang_1_1_i_file_reader.html',1,'irrklang']]],
  ['ifilesystem',['IFileSystem',['../classirr_1_1io_1_1_i_file_system.html',1,'irr::io']]],
  ['igeometrycreator',['IGeometryCreator',['../classirr_1_1scene_1_1_i_geometry_creator.html',1,'irr::scene']]],
  ['igpuprogrammingservices',['IGPUProgrammingServices',['../classirr_1_1video_1_1_i_g_p_u_programming_services.html',1,'irr::video']]],
  ['iguibutton',['IGUIButton',['../classirr_1_1gui_1_1_i_g_u_i_button.html',1,'irr::gui']]],
  ['iguicheckbox',['IGUICheckBox',['../classirr_1_1gui_1_1_i_g_u_i_check_box.html',1,'irr::gui']]],
  ['iguicolorselectdialog',['IGUIColorSelectDialog',['../classirr_1_1gui_1_1_i_g_u_i_color_select_dialog.html',1,'irr::gui']]],
  ['iguicombobox',['IGUIComboBox',['../classirr_1_1gui_1_1_i_g_u_i_combo_box.html',1,'irr::gui']]],
  ['iguicontextmenu',['IGUIContextMenu',['../classirr_1_1gui_1_1_i_g_u_i_context_menu.html',1,'irr::gui']]],
  ['iguieditbox',['IGUIEditBox',['../classirr_1_1gui_1_1_i_g_u_i_edit_box.html',1,'irr::gui']]],
  ['iguielement',['IGUIElement',['../classirr_1_1gui_1_1_i_g_u_i_element.html',1,'irr::gui']]],
  ['iguielementfactory',['IGUIElementFactory',['../classirr_1_1gui_1_1_i_g_u_i_element_factory.html',1,'irr::gui']]],
  ['iguienvironment',['IGUIEnvironment',['../classirr_1_1gui_1_1_i_g_u_i_environment.html',1,'irr::gui']]],
  ['iguifileopendialog',['IGUIFileOpenDialog',['../classirr_1_1gui_1_1_i_g_u_i_file_open_dialog.html',1,'irr::gui']]],
  ['iguifont',['IGUIFont',['../classirr_1_1gui_1_1_i_g_u_i_font.html',1,'irr::gui']]],
  ['iguifontbitmap',['IGUIFontBitmap',['../classirr_1_1gui_1_1_i_g_u_i_font_bitmap.html',1,'irr::gui']]],
  ['iguiimage',['IGUIImage',['../classirr_1_1gui_1_1_i_g_u_i_image.html',1,'irr::gui']]],
  ['iguiimagelist',['IGUIImageList',['../classirr_1_1gui_1_1_i_g_u_i_image_list.html',1,'irr::gui']]],
  ['iguiinoutfader',['IGUIInOutFader',['../classirr_1_1gui_1_1_i_g_u_i_in_out_fader.html',1,'irr::gui']]],
  ['iguilistbox',['IGUIListBox',['../classirr_1_1gui_1_1_i_g_u_i_list_box.html',1,'irr::gui']]],
  ['iguimeshviewer',['IGUIMeshViewer',['../classirr_1_1gui_1_1_i_g_u_i_mesh_viewer.html',1,'irr::gui']]],
  ['iguiscrollbar',['IGUIScrollBar',['../classirr_1_1gui_1_1_i_g_u_i_scroll_bar.html',1,'irr::gui']]],
  ['iguiskin',['IGUISkin',['../classirr_1_1gui_1_1_i_g_u_i_skin.html',1,'irr::gui']]],
  ['iguispinbox',['IGUISpinBox',['../classirr_1_1gui_1_1_i_g_u_i_spin_box.html',1,'irr::gui']]],
  ['iguispritebank',['IGUISpriteBank',['../classirr_1_1gui_1_1_i_g_u_i_sprite_bank.html',1,'irr::gui']]],
  ['iguistatictext',['IGUIStaticText',['../classirr_1_1gui_1_1_i_g_u_i_static_text.html',1,'irr::gui']]],
  ['iguitab',['IGUITab',['../classirr_1_1gui_1_1_i_g_u_i_tab.html',1,'irr::gui']]],
  ['iguitabcontrol',['IGUITabControl',['../classirr_1_1gui_1_1_i_g_u_i_tab_control.html',1,'irr::gui']]],
  ['iguitable',['IGUITable',['../classirr_1_1gui_1_1_i_g_u_i_table.html',1,'irr::gui']]],
  ['iguitoolbar',['IGUIToolBar',['../classirr_1_1gui_1_1_i_g_u_i_tool_bar.html',1,'irr::gui']]],
  ['iguitreeview',['IGUITreeView',['../classirr_1_1gui_1_1_i_g_u_i_tree_view.html',1,'irr::gui']]],
  ['iguitreeviewnode',['IGUITreeViewNode',['../classirr_1_1gui_1_1_i_g_u_i_tree_view_node.html',1,'irr::gui']]],
  ['iguiwindow',['IGUIWindow',['../classirr_1_1gui_1_1_i_g_u_i_window.html',1,'irr::gui']]],
  ['iimage',['IImage',['../classirr_1_1video_1_1_i_image.html',1,'irr::video']]],
  ['iimageloader',['IImageLoader',['../classirr_1_1video_1_1_i_image_loader.html',1,'irr::video']]],
  ['iimagepresenter',['IImagePresenter',['../classirr_1_1video_1_1_i_image_presenter.html',1,'irr::video']]],
  ['iimagewriter',['IImageWriter',['../classirr_1_1video_1_1_i_image_writer.html',1,'irr::video']]],
  ['iindexbuffer',['IIndexBuffer',['../classirr_1_1scene_1_1_i_index_buffer.html',1,'irr::scene']]],
  ['iirrxmlreader',['IIrrXMLReader',['../classirr_1_1io_1_1_i_irr_x_m_l_reader.html',1,'irr::io']]],
  ['iirrxmlreader_3c_20char_5ftype_2c_20superclass_20_3e',['IIrrXMLReader&lt; char_type, superclass &gt;',['../classirr_1_1io_1_1_i_irr_x_m_l_reader.html',1,'irr::io']]],
  ['ilightmanager',['ILightManager',['../classirr_1_1scene_1_1_i_light_manager.html',1,'irr::scene']]],
  ['ilightscenenode',['ILightSceneNode',['../classirr_1_1scene_1_1_i_light_scene_node.html',1,'irr::scene']]],
  ['ilogger',['ILogger',['../classirr_1_1_i_logger.html',1,'irr']]],
  ['ilookinstream',['ILookInStream',['../struct_i_look_in_stream.html',1,'']]],
  ['image_5fpixel',['image_pixel',['../structimage__pixel.html',1,'']]],
  ['image_5ftransform',['image_transform',['../structimage__transform.html',1,'']]],
  ['imaterialrenderer',['IMaterialRenderer',['../classirr_1_1video_1_1_i_material_renderer.html',1,'irr::video']]],
  ['imaterialrendererservices',['IMaterialRendererServices',['../classirr_1_1video_1_1_i_material_renderer_services.html',1,'irr::video']]],
  ['imesh',['IMesh',['../classirr_1_1scene_1_1_i_mesh.html',1,'irr::scene']]],
  ['imeshbuffer',['IMeshBuffer',['../classirr_1_1scene_1_1_i_mesh_buffer.html',1,'irr::scene']]],
  ['imeshcache',['IMeshCache',['../classirr_1_1scene_1_1_i_mesh_cache.html',1,'irr::scene']]],
  ['imeshloader',['IMeshLoader',['../classirr_1_1scene_1_1_i_mesh_loader.html',1,'irr::scene']]],
  ['imeshmanipulator',['IMeshManipulator',['../classirr_1_1scene_1_1_i_mesh_manipulator.html',1,'irr::scene']]],
  ['imeshscenenode',['IMeshSceneNode',['../classirr_1_1scene_1_1_i_mesh_scene_node.html',1,'irr::scene']]],
  ['imeshwriter',['IMeshWriter',['../classirr_1_1scene_1_1_i_mesh_writer.html',1,'irr::scene']]],
  ['imetatriangleselector',['IMetaTriangleSelector',['../classirr_1_1scene_1_1_i_meta_triangle_selector.html',1,'irr::scene']]],
  ['inflate_5fstate',['inflate_state',['../structinflate__state.html',1,'']]],
  ['internal_5fstate',['internal_state',['../structinternal__state.html',1,'']]],
  ['intro',['Intro',['../class_intro.html',1,'']]],
  ['inttofloat',['inttofloat',['../unionirr_1_1core_1_1inttofloat.html',1,'irr::core']]],
  ['iosoperator',['IOSOperator',['../classirr_1_1_i_o_s_operator.html',1,'irr']]],
  ['iparticleaffector',['IParticleAffector',['../classirr_1_1scene_1_1_i_particle_affector.html',1,'irr::scene']]],
  ['iparticleanimatedmeshscenenodeemitter',['IParticleAnimatedMeshSceneNodeEmitter',['../classirr_1_1scene_1_1_i_particle_animated_mesh_scene_node_emitter.html',1,'irr::scene']]],
  ['iparticleattractionaffector',['IParticleAttractionAffector',['../classirr_1_1scene_1_1_i_particle_attraction_affector.html',1,'irr::scene']]],
  ['iparticleboxemitter',['IParticleBoxEmitter',['../classirr_1_1scene_1_1_i_particle_box_emitter.html',1,'irr::scene']]],
  ['iparticlecylinderemitter',['IParticleCylinderEmitter',['../classirr_1_1scene_1_1_i_particle_cylinder_emitter.html',1,'irr::scene']]],
  ['iparticleemitter',['IParticleEmitter',['../classirr_1_1scene_1_1_i_particle_emitter.html',1,'irr::scene']]],
  ['iparticlefadeoutaffector',['IParticleFadeOutAffector',['../classirr_1_1scene_1_1_i_particle_fade_out_affector.html',1,'irr::scene']]],
  ['iparticlegravityaffector',['IParticleGravityAffector',['../classirr_1_1scene_1_1_i_particle_gravity_affector.html',1,'irr::scene']]],
  ['iparticlemeshemitter',['IParticleMeshEmitter',['../classirr_1_1scene_1_1_i_particle_mesh_emitter.html',1,'irr::scene']]],
  ['iparticleringemitter',['IParticleRingEmitter',['../classirr_1_1scene_1_1_i_particle_ring_emitter.html',1,'irr::scene']]],
  ['iparticlerotationaffector',['IParticleRotationAffector',['../classirr_1_1scene_1_1_i_particle_rotation_affector.html',1,'irr::scene']]],
  ['iparticlesphereemitter',['IParticleSphereEmitter',['../classirr_1_1scene_1_1_i_particle_sphere_emitter.html',1,'irr::scene']]],
  ['iparticlesystemscenenode',['IParticleSystemSceneNode',['../classirr_1_1scene_1_1_i_particle_system_scene_node.html',1,'irr::scene']]],
  ['iq3levelmesh',['IQ3LevelMesh',['../classirr_1_1scene_1_1_i_q3_level_mesh.html',1,'irr::scene']]],
  ['irandomizer',['IRandomizer',['../classirr_1_1_i_randomizer.html',1,'irr']]],
  ['ireadfile',['IReadFile',['../classirr_1_1io_1_1_i_read_file.html',1,'irr::io']]],
  ['irefcounted',['IRefCounted',['../classirrklang_1_1_i_ref_counted.html',1,'irrklang']]],
  ['ireferencecounted',['IReferenceCounted',['../classirr_1_1_i_reference_counted.html',1,'irr']]],
  ['irendertarget',['IRenderTarget',['../structirr_1_1video_1_1_i_render_target.html',1,'irr::video']]],
  ['irrallocator',['irrAllocator',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20array_3c_20core_3a_3avector3df_20_3e_20_3e',['irrAllocator&lt; array&lt; core::vector3df &gt; &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20bodypart_20_3e',['irrAllocator&lt; BodyPart &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20bool_20_3e',['irrAllocator&lt; bool &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20c8_20_3e',['irrAllocator&lt; c8 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20cgroupfinder_3a_3asedge_20_3e',['irrAllocator&lt; CGroupFinder::SEdge &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20cgroupfinder_3a_3aslinelist_20_3e',['irrAllocator&lt; CGroupFinder::SLineList &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20cgroupfinder_3a_3aspixelgroup_20_3e',['irrAllocator&lt; CGroupFinder::SPixelGroup &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20char_5ftype_20_3e',['irrAllocator&lt; char_type &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20const_20irr_3a_3ascene_3a_3aiscenenode_20_2a_20_3e',['irrAllocator&lt; const irr::scene::ISceneNode * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3aaabbox3d_3c_20f32_20_3e_20_3e',['irrAllocator&lt; core::aabbox3d&lt; f32 &gt; &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3aarray_3c_20bool_20_3e_20_3e',['irrAllocator&lt; core::array&lt; bool &gt; &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3aarray_3c_20core_3a_3avector2df_20_3e_20_3e',['irrAllocator&lt; core::array&lt; core::vector2df &gt; &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3aarray_3c_20irr_3a_3ascene_3a_3airr_3a_3ascene_3a_3aimeshbuffer_20_2a_20_3e_20_3e',['irrAllocator&lt; core::array&lt; irr::scene::irr::scene::IMeshBuffer * &gt; &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3aarray_3c_20u32_20_3e_20_3e',['irrAllocator&lt; core::array&lt; u32 &gt; &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3aline2df_20_3e',['irrAllocator&lt; core::line2df &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3amatrix4_20_3e',['irrAllocator&lt; core::matrix4 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3aposition2di_20_3e',['irrAllocator&lt; core::position2di &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3astring_3c_20char_5ftype_20_3e_20_3e',['irrAllocator&lt; core::string&lt; char_type &gt; &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3astringc_20_3e',['irrAllocator&lt; core::stringc &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3astringw_20_3e',['irrAllocator&lt; core::stringw &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3atriangle3df_20_3e',['irrAllocator&lt; core::triangle3df &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3avector2df_20_3e',['irrAllocator&lt; core::vector2df &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20core_3a_3avector3df_20_3e',['irrAllocator&lt; core::vector3df &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20defaultnodeentry_20_3e',['irrAllocator&lt; DefaultNodeEntry &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20f32_20_3e',['irrAllocator&lt; f32 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20f64_20_3e',['irrAllocator&lt; f64 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20fschar_5ft_20_3e',['irrAllocator&lt; fschar_t &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3acfonttool_3a_3asfontarea_20_3e',['irrAllocator&lt; irr::CFontTool::SFontArea &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3acore_3a_3amatrix4_20_3e',['irrAllocator&lt; irr::core::matrix4 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3acore_3a_3astringw_20_3e',['irrAllocator&lt; irr::core::stringw &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3agui_3a_3acguiattribute_20_2a_20_3e',['irrAllocator&lt; irr::gui::CGUIAttribute * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3agui_3a_3aiguiimage_20_2a_20_3e',['irrAllocator&lt; irr::gui::IGUIImage * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3agui_3a_3asguispriteframe_20_3e',['irrAllocator&lt; irr::gui::SGUISpriteFrame &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aio_3a_3aiarchiveloader_20_2a_20_3e',['irrAllocator&lt; irr::io::IArchiveLoader * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aio_3a_3aiattribute_20_2a_20_3e',['irrAllocator&lt; irr::io::IAttribute * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aio_3a_3aifilearchive_20_2a_20_3e',['irrAllocator&lt; irr::io::IFileArchive * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aio_3a_3asfilelistentry_20_3e',['irrAllocator&lt; irr::io::SFileListEntry &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aoctree_3a_3asindexchunk_20_3e',['irrAllocator&lt; irr::Octree::SIndexChunk &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aoctree_3c_20video_3a_3as3dvertex_20_3e_3a_3asmeshchunk_20_3e',['irrAllocator&lt; irr::Octree&lt; video::S3DVertex &gt;::SMeshChunk &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aoctree_3c_20video_3a_3as3dvertex2tcoords_20_3e_3a_3asmeshchunk_20_3e',['irrAllocator&lt; irr::Octree&lt; video::S3DVertex2TCoords &gt;::SMeshChunk &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3aoctree_3c_20video_3a_3as3dvertextangents_20_3e_3a_3asmeshchunk_20_3e',['irrAllocator&lt; irr::Octree&lt; video::S3DVertexTangents &gt;::SMeshChunk &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3acanimatedmeshmd2_3a_3asanimationdata_20_3e',['irrAllocator&lt; irr::scene::CAnimatedMeshMD2::SAnimationData &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3acanimatedmeshmd2_3a_3askeyframetransform_20_3e',['irrAllocator&lt; irr::scene::CAnimatedMeshMD2::SKeyFrameTransform &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3acanimatedmeshmd2_3a_3asmd2vert_20_3e',['irrAllocator&lt; irr::scene::CAnimatedMeshMD2::SMD2Vert &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3accolladameshwriter_3a_3amaterialname_20_3e',['irrAllocator&lt; irr::scene::CColladaMeshWriter::MaterialName &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3accolladameshwriter_3a_3asgeometrymeshmaterials_20_3e',['irrAllocator&lt; irr::scene::CColladaMeshWriter::SGeometryMeshMaterials &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aclwomeshfileloader_3a_3atlwomaterial_20_2a_20_3e',['irrAllocator&lt; irr::scene::CLWOMeshFileLoader::tLWOMaterial * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3acmeshcache_3a_3ameshentry_20_3e',['irrAllocator&lt; irr::scene::CMeshCache::MeshEntry &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3acskinnedmesh_3a_3asjoint_20_2a_20_3e',['irrAllocator&lt; irr::scene::CSkinnedMesh::SJoint * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3acxmeshfileloader_3a_3asxmesh_20_2a_20_3e',['irrAllocator&lt; irr::scene::CXMeshFileLoader::SXMesh * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3acxmeshfileloader_3a_3asxtemplatematerial_20_3e',['irrAllocator&lt; irr::scene::CXMeshFileLoader::SXTemplateMaterial &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aibonescenenode_20_2a_20_3e',['irrAllocator&lt; irr::scene::IBoneSceneNode * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aicolladaprefab_20_2a_20_3e',['irrAllocator&lt; irr::scene::IColladaPrefab * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aimesh_20_2a_20_3e',['irrAllocator&lt; irr::scene::IMesh * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aimeshbuffer_20_2a_20_3e',['irrAllocator&lt; irr::scene::IMeshBuffer * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aimeshloader_20_2a_20_3e',['irrAllocator&lt; irr::scene::IMeshLoader * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aisceneloader_20_2a_20_3e',['irrAllocator&lt; irr::scene::ISceneLoader * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiscenenode_20_2a_20_3e',['irrAllocator&lt; irr::scene::ISceneNode * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiscenenodeanimatorfactory_20_2a_20_3e',['irrAllocator&lt; irr::scene::ISceneNodeAnimatorFactory * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiscenenodefactory_20_2a_20_3e',['irrAllocator&lt; irr::scene::ISceneNodeFactory * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiskinnedmesh_3a_3asjoint_20_2a_20_3e',['irrAllocator&lt; irr::scene::ISkinnedMesh::SJoint * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiskinnedmesh_3a_3aspositionkey_20_3e',['irrAllocator&lt; irr::scene::ISkinnedMesh::SPositionKey &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiskinnedmesh_3a_3asrotationkey_20_3e',['irrAllocator&lt; irr::scene::ISkinnedMesh::SRotationKey &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiskinnedmesh_3a_3asscalekey_20_3e',['irrAllocator&lt; irr::scene::ISkinnedMesh::SScaleKey &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aiskinnedmesh_3a_3asweight_20_3e',['irrAllocator&lt; irr::scene::ISkinnedMesh::SWeight &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aitriangleselector_20_2a_20_3e',['irrAllocator&lt; irr::scene::ITriangleSelector * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aquake3_3a_3asvargroup_20_3e',['irrAllocator&lt; irr::scene::quake3::SVarGroup &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3aquake3_3a_3asvariable_20_3e',['irrAllocator&lt; irr::scene::quake3::SVariable &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asaccessor_20_3e',['irrAllocator&lt; irr::scene::SAccessor &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3ascolladaeffect_20_3e',['irrAllocator&lt; irr::scene::SColladaEffect &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3ascolladaimage_20_3e',['irrAllocator&lt; irr::scene::SColladaImage &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3ascolladainput_20_3e',['irrAllocator&lt; irr::scene::SColladaInput &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3ascolladamaterial_20_3e',['irrAllocator&lt; irr::scene::SColladaMaterial &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3ascolladaparam_20_3e',['irrAllocator&lt; irr::scene::SColladaParam &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3ascolladatexture_20_3e',['irrAllocator&lt; irr::scene::SColladaTexture &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asmd3meshbuffer_20_2a_20_3e',['irrAllocator&lt; irr::scene::SMD3MeshBuffer * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asmd3quaterniontag_20_3e',['irrAllocator&lt; irr::scene::SMD3QuaternionTag &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asmd3texcoord_20_3e',['irrAllocator&lt; irr::scene::SMD3TexCoord &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asmd3vertex_20_3e',['irrAllocator&lt; irr::scene::SMD3Vertex &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asparticle_20_3e',['irrAllocator&lt; irr::scene::SParticle &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asskinmeshbuffer_20_2a_20_3e',['irrAllocator&lt; irr::scene::SSkinMeshBuffer * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3astextureatlas_3a_3atextureatlasentry_20_3e',['irrAllocator&lt; irr::scene::STextureAtlas::TextureAtlasEntry &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3ascene_3a_3asubmodel_20_3e',['irrAllocator&lt; irr::scene::SubModel &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3askeymap_20_3e',['irrAllocator&lt; irr::SKeyMap &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3avideo_3a_3acnulldriver_3a_3asmaterialrenderer_20_3e',['irrAllocator&lt; irr::video::CNullDriver::SMaterialRenderer &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3avideo_3a_3acnulldriver_3a_3asoccquery_20_3e',['irrAllocator&lt; irr::video::CNullDriver::SOccQuery &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3avideo_3a_3acnulldriver_3a_3assurface_20_3e',['irrAllocator&lt; irr::video::CNullDriver::SSurface &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3avideo_3a_3as2dvertex_20_3e',['irrAllocator&lt; irr::video::S2DVertex &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3avideo_3a_3asburningshaderlight_20_3e',['irrAllocator&lt; irr::video::SBurningShaderLight &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3avideo_3a_3asirrvideoclip_20_2a_20_3e',['irrAllocator&lt; irr::video::SIrrVideoClip * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20irr_3a_3avideo_3a_3aslight_20_3e',['irrAllocator&lt; irr::video::SLight &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20keyframeinterpolation_20_3e',['irrAllocator&lt; KeyFrameInterpolation &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogreanimation_20_3e',['irrAllocator&lt; OgreAnimation &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogrebone_20_3e',['irrAllocator&lt; OgreBone &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogreboneassignment_20_3e',['irrAllocator&lt; OgreBoneAssignment &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogrekeyframe_20_3e',['irrAllocator&lt; OgreKeyframe &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogrematerial_20_3e',['irrAllocator&lt; OgreMaterial &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogremesh_20_3e',['irrAllocator&lt; OgreMesh &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogrepass_20_3e',['irrAllocator&lt; OgrePass &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogresubmesh_20_3e',['irrAllocator&lt; OgreSubMesh &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogretechnique_20_3e',['irrAllocator&lt; OgreTechnique &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogretexturealias_20_3e',['irrAllocator&lt; OgreTextureAlias &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogrevertexbuffer_20_3e',['irrAllocator&lt; OgreVertexBuffer &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ogrevertexelement_20_3e',['irrAllocator&lt; OgreVertexElement &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20quake3_3a_3aishader_20_3e',['irrAllocator&lt; quake3::IShader &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20s32_20_3e',['irrAllocator&lt; s32 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20s3dvertex_20_3e',['irrAllocator&lt; S3DVertex &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20s3dvertex2tcoords_5f64_20_3e',['irrAllocator&lt; S3DVertex2TCoords_64 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sattribute_20_3e',['irrAllocator&lt; SAttribute &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sb3dchunk_20_3e',['irrAllocator&lt; SB3dChunk &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sb3dmaterial_20_3e',['irrAllocator&lt; SB3dMaterial &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sb3dtexture_20_3e',['irrAllocator&lt; SB3dTexture &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20scene_3a_3airr_3a_3ascene_3a_3asskinmeshbuffer_20_2a_20_3e',['irrAllocator&lt; scene::irr::scene::SSkinMeshBuffer * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20scurrentmaterial_20_3e',['irrAllocator&lt; SCurrentMaterial &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sgeomipmaptrianglepatch_20_3e',['irrAllocator&lt; SGeoMipMapTrianglePatch &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sjoint_20_2a_20_3e',['irrAllocator&lt; SJoint * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sklistnode_20_3e',['irrAllocator&lt; SKListNode &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20smaterialgroup_20_3e',['irrAllocator&lt; SMaterialGroup &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20smymaterialentry_20_3e',['irrAllocator&lt; SMyMaterialEntry &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20smymeshbufferentry_20_3e',['irrAllocator&lt; SMyMeshBufferEntry &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sobjmtl_20_2a_20_3e',['irrAllocator&lt; SObjMtl * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20splyelement_20_2a_20_3e',['irrAllocator&lt; SPLYElement * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20splyproperty_20_3e',['irrAllocator&lt; SPLYProperty &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sq3texture_20_3e',['irrAllocator&lt; SQ3Texture &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20sscenenodetypepair_20_3e',['irrAllocator&lt; SSceneNodeTypePair &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20ssymbolinfo_20_3e',['irrAllocator&lt; SSymbolInfo &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20stexshader_20_3e',['irrAllocator&lt; STexShader &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20svideomode_20_3e',['irrAllocator&lt; SVideoMode &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20transparentnodeentry_20_3e',['irrAllocator&lt; TransparentNodeEntry &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20u16_20_3e',['irrAllocator&lt; u16 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20u32_20_3e',['irrAllocator&lt; u32 &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3aiimage_20_2a_20_3e',['irrAllocator&lt; video::IImage * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3airr_3a_3avideo_3a_3aiimageloader_20_2a_20_3e',['irrAllocator&lt; video::irr::video::IImageLoader * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3airr_3a_3avideo_3a_3aiimagewriter_20_2a_20_3e',['irrAllocator&lt; video::irr::video::IImageWriter * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3aitexture_20_2a_20_3e',['irrAllocator&lt; video::ITexture * &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3as3dvertex_20_3e',['irrAllocator&lt; video::S3DVertex &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3as3dvertex2tcoords_20_3e',['irrAllocator&lt; video::S3DVertex2TCoords &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3as3dvertextangents_20_3e',['irrAllocator&lt; video::S3DVertexTangents &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20video_3a_3asmaterial_20_3e',['irrAllocator&lt; video::SMaterial &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocator_3c_20wchar_5ft_20_3e',['irrAllocator&lt; wchar_t &gt;',['../classirr_1_1core_1_1irr_allocator.html',1,'irr::core']]],
  ['irrallocatorfast',['irrAllocatorFast',['../classirr_1_1core_1_1irr_allocator_fast.html',1,'irr::core']]],
  ['irrlichtcontroller',['IrrlichtController',['../class_irrlicht_controller.html',1,'']]],
  ['irrlichtdevice',['IrrlichtDevice',['../classirr_1_1_irrlicht_device.html',1,'irr']]],
  ['iscenecollisionmanager',['ISceneCollisionManager',['../classirr_1_1scene_1_1_i_scene_collision_manager.html',1,'irr::scene']]],
  ['isceneloader',['ISceneLoader',['../classirr_1_1scene_1_1_i_scene_loader.html',1,'irr::scene']]],
  ['iscenemanager',['ISceneManager',['../classirr_1_1scene_1_1_i_scene_manager.html',1,'irr::scene']]],
  ['iscenenode',['ISceneNode',['../classirr_1_1scene_1_1_i_scene_node.html',1,'irr::scene']]],
  ['iscenenodeanimator',['ISceneNodeAnimator',['../classirr_1_1scene_1_1_i_scene_node_animator.html',1,'irr::scene']]],
  ['iscenenodeanimatorcamerafps',['ISceneNodeAnimatorCameraFPS',['../classirr_1_1scene_1_1_i_scene_node_animator_camera_f_p_s.html',1,'irr::scene']]],
  ['iscenenodeanimatorcameramaya',['ISceneNodeAnimatorCameraMaya',['../classirr_1_1scene_1_1_i_scene_node_animator_camera_maya.html',1,'irr::scene']]],
  ['iscenenodeanimatorcollisionresponse',['ISceneNodeAnimatorCollisionResponse',['../classirr_1_1scene_1_1_i_scene_node_animator_collision_response.html',1,'irr::scene']]],
  ['iscenenodeanimatorfactory',['ISceneNodeAnimatorFactory',['../classirr_1_1scene_1_1_i_scene_node_animator_factory.html',1,'irr::scene']]],
  ['iscenenodeanimatorfinishing',['ISceneNodeAnimatorFinishing',['../classirr_1_1scene_1_1_i_scene_node_animator_finishing.html',1,'irr::scene']]],
  ['iscenenodefactory',['ISceneNodeFactory',['../classirr_1_1scene_1_1_i_scene_node_factory.html',1,'irr::scene']]],
  ['isceneuserdataserializer',['ISceneUserDataSerializer',['../classirr_1_1scene_1_1_i_scene_user_data_serializer.html',1,'irr::scene']]],
  ['iseekinstream',['ISeekInStream',['../struct_i_seek_in_stream.html',1,'']]],
  ['iselectionbox',['ISelectionBox',['../class_i_selection_box.html',1,'']]],
  ['iseqinstream',['ISeqInStream',['../struct_i_seq_in_stream.html',1,'']]],
  ['iseqoutstream',['ISeqOutStream',['../struct_i_seq_out_stream.html',1,'']]],
  ['iserialize',['ISerialize',['../class_i_serialize.html',1,'']]],
  ['ishader',['IShader',['../structirr_1_1scene_1_1quake3_1_1_i_shader.html',1,'irr::scene::quake3']]],
  ['ishaderconstantsetcallback',['IShaderConstantSetCallBack',['../classirr_1_1video_1_1_i_shader_constant_set_call_back.html',1,'irr::video']]],
  ['ishadermanager',['IShaderManager',['../classirr_1_1scene_1_1quake3_1_1_i_shader_manager.html',1,'irr::scene::quake3']]],
  ['ishadowvolumescenenode',['IShadowVolumeSceneNode',['../classirr_1_1scene_1_1_i_shadow_volume_scene_node.html',1,'irr::scene']]],
  ['iskinnedmesh',['ISkinnedMesh',['../classirr_1_1scene_1_1_i_skinned_mesh.html',1,'irr::scene']]],
  ['isound',['ISound',['../classirrklang_1_1_i_sound.html',1,'irrklang']]],
  ['isounddevicelist',['ISoundDeviceList',['../classirrklang_1_1_i_sound_device_list.html',1,'irrklang']]],
  ['isoundeffectcontrol',['ISoundEffectControl',['../classirrklang_1_1_i_sound_effect_control.html',1,'irrklang']]],
  ['isoundengine',['ISoundEngine',['../classirrklang_1_1_i_sound_engine.html',1,'irrklang']]],
  ['isoundmixedoutputreceiver',['ISoundMixedOutputReceiver',['../classirrklang_1_1_i_sound_mixed_output_receiver.html',1,'irrklang']]],
  ['isoundsource',['ISoundSource',['../classirrklang_1_1_i_sound_source.html',1,'irrklang']]],
  ['isoundstopeventreceiver',['ISoundStopEventReceiver',['../classirrklang_1_1_i_sound_stop_event_receiver.html',1,'irrklang']]],
  ['istencilbuffer',['IStencilBuffer',['../classirr_1_1video_1_1_i_stencil_buffer.html',1,'irr::video']]],
  ['iszalloc',['ISzAlloc',['../struct_i_sz_alloc.html',1,'']]],
  ['itemminebomb',['ItemMineBomb',['../class_item_mine_bomb.html',1,'']]],
  ['itemthrow',['ItemThrow',['../class_item_throw.html',1,'']]],
  ['iterator',['Iterator',['../classirr_1_1core_1_1map_1_1_iterator.html',1,'irr::core::map']]],
  ['iterator',['Iterator',['../classirr_1_1core_1_1list_1_1_iterator.html',1,'irr::core::list']]],
  ['iterrainscenenode',['ITerrainSceneNode',['../classirr_1_1scene_1_1_i_terrain_scene_node.html',1,'irr::scene']]],
  ['itextscenenode',['ITextSceneNode',['../classirr_1_1scene_1_1_i_text_scene_node.html',1,'irr::scene']]],
  ['itexture',['ITexture',['../classirr_1_1video_1_1_i_texture.html',1,'irr::video']]],
  ['itimer',['ITimer',['../classirr_1_1_i_timer.html',1,'irr']]],
  ['itrianglerenderer',['ITriangleRenderer',['../classirr_1_1video_1_1_i_triangle_renderer.html',1,'irr::video']]],
  ['itriangleselector',['ITriangleSelector',['../classirr_1_1scene_1_1_i_triangle_selector.html',1,'irr::scene']]],
  ['ivertexbuffer',['IVertexBuffer',['../classirr_1_1scene_1_1_i_vertex_buffer.html',1,'irr::scene']]],
  ['ivertexmanipulator',['IVertexManipulator',['../structirr_1_1scene_1_1_i_vertex_manipulator.html',1,'irr::scene']]],
  ['ivideodriver',['IVideoDriver',['../classirr_1_1video_1_1_i_video_driver.html',1,'irr::video']]],
  ['ivideomodelist',['IVideoModeList',['../classirr_1_1video_1_1_i_video_mode_list.html',1,'irr::video']]],
  ['ivirtualrefcounted',['IVirtualRefCounted',['../classirrklang_1_1_i_virtual_ref_counted.html',1,'irrklang']]],
  ['ivolumelightscenenode',['IVolumeLightSceneNode',['../classirr_1_1scene_1_1_i_volume_light_scene_node.html',1,'irr::scene']]],
  ['iwritefile',['IWriteFile',['../classirr_1_1io_1_1_i_write_file.html',1,'irr::io']]],
  ['ixmlbase',['IXMLBase',['../classirr_1_1io_1_1_i_x_m_l_base.html',1,'irr::io']]],
  ['ixmlwriter',['IXMLWriter',['../classirr_1_1io_1_1_i_x_m_l_writer.html',1,'irr::io']]],
  ['izbuffer',['IZBuffer',['../classirr_1_1video_1_1_i_z_buffer.html',1,'irr::video']]]
];
